abc/config/routes.rb
Rails.application.routes.draw do
  resources :rols
  resources :departments
  resources :pqr_files
  devise_for :users
  resources :pqrs
  get 'home/index'
  root'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

abc/app/models/pqr.rb
class Pqr < ApplicationRecord
 belongs_to :user
end

abc/app/controllers/pqrs_controller.rb
class PqrsController < ApplicationController
  before_action :set_pqr, only: [:show, :edit, :update, :destroy]

  # GET /pqrs
  # GET /pqrs.json
  def index
    @pqrs = Pqr.all
  end

  # GET /pqrs/1
  # GET /pqrs/1.json
  def show
  end

  # GET /pqrs/new
  def new
    @pqr = Pqr.new
  end

  # GET /pqrs/1/edit
  def edit
  end

  # POST /pqrs
  # POST /pqrs.json
  def create
    @pqr = Pqr.new(pqr_params)
    @pqr.user = current_user
    respond_to do |format|
      if @pqr.save
        format.html { redirect_to @pqr, notice: 'Pqr was successfully created.' }
        format.json { render :show, status: :created, location: @pqr }
      else
        format.html { render :new }
        format.json { render json: @pqr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pqrs/1
  # PATCH/PUT /pqrs/1.json
  def update
    respond_to do |format|
      if @pqr.update(pqr_params)
        format.html { redirect_to @pqr, notice: 'Pqr was successfully updated.' }
        format.json { render :show, status: :ok, location: @pqr }
      else
        format.html { render :edit }
        format.json { render json: @pqr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pqrs/1
  # DELETE /pqrs/1.json
  def destroy
    @pqr.destroy
    respond_to do |format|
      format.html { redirect_to pqrs_url, notice: 'Pqr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 private
    # Use callbacks to share common setup or constraints between actions.
    def set_pqr
      @pqr = Pqr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pqr_params
      params.require(:pqr).permit(:first_name, :last_name, :email, :title, :subject, :body,:user_id)
    end
end

abc/app/helpers/pqrs_helper.rb
module PqrsHelper
end

abc/app/views/pqrs/_form.html.erb
<%= form_with(model: pqr, local: true) do |form| %>
  <% if pqr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pqr.errors.count, "error") %> prohibited this pqr from being saved:</h2>

      <ul>
      <% pqr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
    <% unless user_signed_in? %>

        <div class="field col s12 m6">
            <%= form.label :first_name %>
            <%= form.text_field :first_name %>
        </div>

        <div class="field col s12 m6">
            <%= form.label :last_name %>
            <%= form.text_field :last_name %>
        </div>

        <div class="field col s12 m6">
            <%= form.label :email %>
            <%= form.text_field :email %>
        </div>

    <% end %>

    <div class="field col s12 m6">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div class="field col s12 m6">
        <%= form.label :subject %>
        <%= form.text_field :subject %>
    </div>

    <div class="field col s12 m6">
        <%= form.label :body %>
        <%= form.text_area :body %>
    </div>


    <div class="field col s12 m6">
        <%= form.label :pqr_files_id %>
        <%= form.text_field :pqr_files_id, value:'1' %>
    </div>

</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<input type="file">

abc/app/views/pqrs/edit.html.erb
<h1>Editing Pqr</h1>

<%= render 'form', pqr: @pqr %>

<%= link_to 'Show', @pqr %> |
<%= link_to 'Back', pqrs_path %>

abc/app/views/pqrs/index.html.erb
<div class="container">
    <div class="row">
        <br>
        <div class="col s12">
            <div class="card-panel">
        <h5 class="center">PQRS</h1>
                    <p id="notice"><%= notice %></p>

                    <table>
                      <thead>
                        <tr>
                          <th>First name</th>
                          <th>Last name</th>
                          <th>Email</th>
                          <th>Title</th>
                          <th>Subject</th>
                          <th>Body</th>
                          >
                          
                          <th>Pqr files</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>

                      <tbody>
                        <% @pqrs.each do |pqr| %>
                          <tr>
                            <td><%= pqr.first_name %></td>
                            <td><%= pqr.last_name %></td>
                            <td><%= pqr.email %></td>
                            <td><%= pqr.title %></td>
                            <td><%= pqr.subject %></td>
                            <td><%= pqr.body %></td>
                            
                            <td><%= pqr.pqr_files %></td>
                          
                            <td><%= link_to 'Show', pqr %></td>
                              <% if current_user && current_user.admin
                                 %> 
                            <td><%= link_to 'Edit', edit_pqr_path(pqr) %></td>
                            <td><%= link_to 'Destroy', pqr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>

                    <br>

                    <%= link_to 'Crear Pqr', new_pqr_path, class:'btn pink' %>


            </div>
      </div>
  </div>
</div>

abc/app/views/pqrs/new.html.erb
<h1<div class="container">
    <div class="row">
        <br>
        <div class="col s12">
            <div class="card-panel">
				<h5 class="center">PQRs</h1>
        
                <%= render 'form', pqr: @pqr %>

                <%= link_to 'Back', pqrs_path %>

            </div>
	    </div>
	</div>
</div>

abc/app/views/pqrs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pqr_path(@pqr) %> |
<%= link_to 'Back', pqrs_path %>