abc/config/routes.rb
Rails.application.routes.draw do
  resources :rols
  resources :departments
  resources :pqr_files
  devise_for :users
  resources :pqrs
  get 'home/index'
  root'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

abc/app/models/pqr_file.rb
class PqrFile < ApplicationRecord
end

abc/app/controllers/pqr_files_controller.rb
class PqrFilesController < ApplicationController
  before_action :set_pqr_file, only: [:show, :edit, :update, :destroy]

  # GET /pqr_files
  # GET /pqr_files.json
  def index
    @pqr_files = PqrFile.all
  end

  # GET /pqr_files/1
  # GET /pqr_files/1.json
  def show
  end

  # GET /pqr_files/new
  def new
    @pqr_file = PqrFile.new
  end

  # GET /pqr_files/1/edit
  def edit
  end

  # POST /pqr_files
  # POST /pqr_files.json
  def create
    @pqr_file = PqrFile.new(pqr_file_params)

    respond_to do |format|
      if @pqr_file.save
        format.html { redirect_to @pqr_file, notice: 'Pqr file was successfully created.' }
        format.json { render :show, status: :created, location: @pqr_file }
      else
        format.html { render :new }
        format.json { render json: @pqr_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pqr_files/1
  # PATCH/PUT /pqr_files/1.json
  def update
    respond_to do |format|
      if @pqr_file.update(pqr_file_params)
        format.html { redirect_to @pqr_file, notice: 'Pqr file was successfully updated.' }
        format.json { render :show, status: :ok, location: @pqr_file }
      else
        format.html { render :edit }
        format.json { render json: @pqr_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pqr_files/1
  # DELETE /pqr_files/1.json
  def destroy
    @pqr_file.destroy
    respond_to do |format|
      format.html { redirect_to pqr_files_url, notice: 'Pqr file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pqr_file
      @pqr_file = PqrFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pqr_file_params
      params.require(:pqr_file).permit(:url)
    end
end

abc/app/helpers/pqr_files_helper.rb
module PqrFilesHelper
end

abc/app/views/pqr_files/_form.html.erb
<%= form_with(model: pqr_file, local: true) do |form| %>
  <% if pqr_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pqr_file.errors.count, "error") %> prohibited this pqr_file from being saved:</h2>

      <ul>
      <% pqr_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

abc/app/views/pqr_files/edit.html.erb
<h1>Editing Pqr File</h1>

<%= render 'form', pqr_file: @pqr_file %>

<%= link_to 'Show', @pqr_file %> |
<%= link_to 'Back', pqr_files_path %>

abc/app/views/pqr_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pqr Files</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pqr_files.each do |pqr_file| %>
      <tr>
        <td><%= link_to 'Show', pqr_file %></td>
        <td><%= link_to 'Edit', edit_pqr_file_path(pqr_file) %></td>
        <td><%= link_to 'Destroy', pqr_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pqr File', new_pqr_file_path %>

abc/app/views/pqr_files/new.html.erb
<h1>New Pqr File</h1>

<%= render 'form', pqr_file: @pqr_file %>

<%= link_to 'Back', pqr_files_path %>

abc/app/views/pqr_files/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pqr_file_path(@pqr_file) %> |
<%= link_to 'Back', pqr_files_path %>